name: fetch_client
description: >
  Client for http package based on Fetch API, enables streamed and cancelable
  requests on web and more.
version: 1.1.2
homepage: https://github.com/Zekfad/fetch_client
repository: https://github.com/Zekfad/fetch_client
issue_tracker: https://github.com/Zekfad/fetch_client/issues
# documentation: https://pub.dev/documentation/fetch_client/latest/
topics:
  - web
  - fetch
  - http

platforms:
  web:

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  fetch_api: ^2.2.0
  http: ^1.2.0

dev_dependencies:
  build_runner: '>=2.4.10'
  build_web_compilers: '>=4.0.10'
  http_client_conformance_tests:
    git:
      url: https://github.com/dart-lang/http
      ref: master
      path: pkgs/http_client_conformance_tests
  test: ^1.25.5
  zekfad_lints: ^2.0.0
